# Application Name
spring.application.name=EventSphere-Backend

# Database Connection Properties
spring.datasource.url=jdbc:mysql://eventspheredb.cpa8a2yoo6zn.eu-north-1.rds.amazonaws.com:3306/eventsphere
spring.datasource.username=admin
spring.datasource.password=EventSphere#1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080

# Logging Properties
logging.level.org.springframework.security=DEBUG
debug=true
